services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'

  app:
    build: .
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - mysql
    restart: always
    command: npm run start:prod

volumes:
  mysql_data:
