version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: hrd_conference_backend
    build: .
    env_file:
      - .env
    ports:
      - '80:3000' # Changed from '${PORT}:${PORT}' to expose app on port 80
    depends_on:
      - mysql
    restart: always
    command: npm run start:prod

volumes:
  mysql_data:
